### ISSUE TITLE
Only op-PrintStarted works.

### ISSUE THREAD

**Issue by AFE-Foreman** [sedgett/OctoPrint_IFTTTmaker#11]
Hello! I was happy to find out about this plugin, but I can't seem to get it working besides notifying me when starting the print. So it is not very useful in this state.

I set everything up with Webhooks and IFTTT as instructed in the readme, and in Octoprint (version 1.3.6) I put in my webhooks key and enabled op-PrintStarted, op-PrintCancelled, op-PrintFailed, and op-PrintDone.  I have each of these triggers set up in IFTTT to send me an SMS text message, however only the op-PrintStarted event works.  Otherwise I do not get a text message.  I have typed everything correctly in Webhooks.

Could you help me resolve this issue? Much appreciated!

![ifttt_octoprint_plugin_issue](https://user-images.githubusercontent.com/7517366/37850990-37b1475c-2eab-11e8-8ff3-dc60e157a336.jpg)
![octoprint_ifttt_settings](https://user-images.githubusercontent.com/7517366/37851125-b53de5e0-2eab-11e8-9a7a-c2435b0a41a3.jpg)

**Comment by AFE-Foreman** [comment]
@sedgett Is there any fix for this?

**Comment by sedgett** [comment]
Hi Matt,

Need some more data...

ClientOpened is a good one to use for testing (each HTTP session triggers the event, so simply refreshing the browser will allow you to test).  Does it work?

Also checkout https://ifttt.com/activity to see what ifttt thinks is happening.

Finally, check the octoprint logfiles... usually /home/pi/.octoprint/logs.   Try the command:
tail -f /home/pi/.octoprint/logs/octoprint.log | grep IFTTT

Let me know what you see there...

**Comment by AFE-Foreman** [comment]
Very late on this, but now closing this because everything is working with current versions. I am using this to relay messages to GroupMe now that SMS is no longer free from IFTTT.
