### ISSUE TITLE
print done event not sent 

### ISSUE THREAD

**Issue by broncosis** [sedgett/OctoPrint_IFTTTmaker#2]
I have tried every which way 
to configure it I can' get the print done to send the event 

I wish there was better loging on ifttt
I will be looking further into this

**Comment by sedgett** [comment]
Hi,

There is debugging info in the octoprint logfile; but you might try
manually triggering the event from your web browser - you get a tiny bit
more info back this way.  Here is the URL it calls.... just replace the
INSERTYOURKEYHERE section.

https://maker.ifttt.com/trigger/op-PrintDone/with/key/
INSERTYOURKEYHERE?value1=TestValue1&value2=TestValue2&value3=TestValue3

**Comment by broncosis** [comment]
why I didn't think of that of course I can make a web call it works but I can't see it triggered in the log anywhere


⁣Sent from BlueMail ​

**Comment by sedgett** [comment]
added extra debugging; now shows payload and response in normal log
