### ISSUE TITLE
Nothing displays in settings

### ISSUE THREAD

**Issue by aaronbarker** [sedgett/OctoPrint_IFTTTmaker#3]
Maybe the project is dead, but I installed this and when I go into the settings it is blank. Any suggestions?

**Comment by SoundGuy** [comment]
same here. Is project dead?

**Comment by sedgett** [comment]
Updated jinga template

**Comment by aaronbarker** [comment]
I saw that this was closed so updated my local version, thank you for working on it! Unfortunately I still don't see anything in the settings after OctoPrint reports a successful install and I refresh the page :(

I'm on OctoPrint 1.3.6

**Comment by SoundGuy** [comment]
so does thing plug in work now?
Is it expected to ? I would love to see this happen.

**Comment by SoundGuy** [comment]
I just uninstalled the plugin and reinstalled from the github master repository URL and it still doesn't show on settings. i'm also on Octoptinr 1.3.6
consider re-opening this issue until resolve?

**Comment by sedgett** [comment]
I just pushed a tiny patch to force an octoprint restart; let me know if it works with a restart. 
If fail, can you confirm what ver octoprint and which platform.

**Comment by SoundGuy** [comment]
I'll retry to uninstall and install again
I'm using Latest Octoprint 1.3.6
are there any logs i can look at if i don't see it? 

never coded a plugin in Octoprint before or in python but if you want me to try to look at the code somewhere to also figure it out i'd be happy to

**Comment by aaronbarker** [comment]
I did a manual restart of octoprint and now it shows up. Thanks!!

**Comment by SoundGuy** [comment]
now it appears in the settings ! Thank you very much. gonna try to see if it sends messages now

**Comment by SoundGuy** [comment]
I added my key and a recipe  for "op-ClientOpened" and it wasn't activated when i restarted (i manually checked ifi confiured it correctly in IFTTT and it seemeedt to have worked)
I will see if I get the print done print next time i finish a print.

is there a way to add a "test event" button just to see if the trigger works?

**Comment by aaronbarker** [comment]
I'm not in a spot where I can try a print, but I did try using the `op-ClientOpened` event and then refreshed my OP interface and I did get a notification. So appears to have worked for me :)

**Comment by sedgett** [comment]
see ~pi/.octoprint/logs.   The plugin logs the url and json it posts.   Adding a test button is a good idea.....

**Comment by SoundGuy** [comment]
Update : 
I went and saw this in the log
2018-02-15 10:59:35,318 - octoprint.plugins.IFTTTmaker - INFO - Trigger: op-ClientOpened Response: {"errors":[{"message":"You sent an invalid key."}]} Payload: {'value3': '192.168.1.5', 'value2': '', 'value1': ''}
realized i had a typo in my IFTTT key (i copied one charachter less).

now - it is sending the message.
However for somerason it sent 3  of these when it restarted:
2018-02-15 11:23:03,022 - octoprint.plugins.IFTTTmaker - INFO - Trigger: op-ClientOpened Response: Congratulations! You've fired the op-ClientOpened event Payload: {'value3': '127.0.0.1', 'value2': '', 'value1': ''}
2018-02-15 11:23:13,652 - octoprint.plugins.IFTTTmaker - INFO - Trigger: op-ClientOpened Response: Congratulations! You've fired the op-ClientOpened event Payload: {'value3': '192.168.1.5', 'value2': '', 'value1': ''}
2018-02-15 11:23:18,545 - octoprint.plugins.IFTTTmaker - INFO - Trigger: op-ClientOpened Response: Congratulations! You've fired the op-ClientOpened event Payload: {'value3': '192.168.1.5', 'value2': '', 'value1': ''}



this is strange but not a critical issue for me.

Thanks for the help! I'm going to make good use of this plug in!

**Comment by SoundGuy** [comment]
Oh, I see why. 
I though this was an event for server start - but now i understand that each of these is a different browser window connected to it.

**Comment by sedgett** [comment]
Not 100% sure why, but restarting seems to resolve settings issue.   added the flag to require a restart.   should be resolved.   if anyone still has troubles, feel free to comment and i'll reopen. :)
