### ISSUE TITLE
Bad pip update URL

### ISSUE THREAD

**Issue by darkvertex** [sedgett/OctoPrint_IFTTTmaker#5]
Hi! In this line:
https://github.com/sedgett/OctoPrint_IFTTTmaker/blob/3248823ad62564b88889babf152079c4213d1360/octoprint_IFTTTmaker/__init__.py#L98
...you define `https://github.com/sedgett/OctoPrint-IFTTTmaker/archive/{target_version}.zip`
but it should be: `https://github.com/sedgett/OctoPrint_IFTTTmaker/archive/{target_version}.zip`

Looks like at some point you renamed the repo from `OctoPrint-IFTTTmaker` to `OctoPrint_IFTTTmaker` but forgot to update this line.

Can you fix it? Updating is broken in the plugin manager...

```

Updating, please wait.
Collecting https://github.com/sedgett/OctoPrint-IFTTTmaker/archive/1.1.1.zip
HTTP error 404 while getting https://github.com/sedgett/OctoPrint-IFTTTmaker/archive/1.1.1.zip
Could not install requirement https://github.com/sedgett/OctoPrint-IFTTTmaker/archive/1.1.1.zip because of error 404 Client Error: Not Found for url: https://github.com/sedgett/OctoPrint-IFTTTmaker/archive/1.1.1.zip
Could not install requirement https://github.com/sedgett/OctoPrint-IFTTTmaker/archive/1.1.1.zip because of HTTP error 404 Client Error: Not Found for url: https://github.com/sedgett/OctoPrint-IFTTTmaker/archive/1.1.1.zip for URL https://github.com/sedgett/OctoPrint-IFTTTmaker/archive/1.1.1.zip
```

**Comment by sedgett** [comment]
Fixed the version number; now 1.3.0

**Comment by sedgett** [comment]
You will need to uninstall and re-install to get the correct update url.

**Comment by darkvertex** [comment]
Ok, thanks for the tip and the fix!
